"""empty message

Revision ID: 44f89149dbd2
Revises: 36f3ba12d5e5
Create Date: 2016-05-04 18:50:01.753213

"""

# revision identifiers, used by Alembic.
revision = '44f89149dbd2'
down_revision = '36f3ba12d5e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_messages',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('short', sa.Text(), nullable=False),
    sa.Column('full', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_', name=op.f('pk_status_messages'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_messages')
    ### end Alembic commands ###
