"""empty message

Revision ID: 47af8d4cbebb
Revises: c60d78465916
Create Date: 2016-05-16 18:04:44.385291

"""

# revision identifiers, used by Alembic.
revision = '47af8d4cbebb'
down_revision = 'c60d78465916'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short', sa.Text(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('short')

    ### end Alembic commands ###
