"""empty message

Revision ID: 52228ccc97f8
Revises: 91eaa66e9b45
Create Date: 2016-12-20 13:14:07.853634

"""

# revision identifiers, used by Alembic.
revision = '52228ccc97f8'
down_revision = '91eaa66e9b45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paycom_number', sa.Text(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('paycom_number')

    ### end Alembic commands ###
