"""empty message

Revision ID: 72513ef34f5e
Revises: 47af8d4cbebb
Create Date: 2016-05-19 20:17:43.308443

"""

# revision identifiers, used by Alembic.
revision = '72513ef34f5e'
down_revision = '47af8d4cbebb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.Text(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    ### end Alembic commands ###
