"""empty message

Revision ID: 91eaa66e9b45
Revises: 72513ef34f5e
Create Date: 2016-11-16 06:59:32.578443

"""

# revision identifiers, used by Alembic.
revision = '91eaa66e9b45'
down_revision = '72513ef34f5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sticks', sa.Text(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('sticks')

    ### end Alembic commands ###
