"""empty message

Revision ID: c60d78465916
Revises: 44f89149dbd2
Create Date: 2016-05-06 15:14:59.118174

"""

# revision identifiers, used by Alembic.
revision = 'c60d78465916'
down_revision = '44f89149dbd2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Text(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('time')

    ### end Alembic commands ###
